[workspace]
resolver = "2"
members = ["leptos-routes", "leptos-routes-macro"]
default-members = ["leptos-routes"]

[workspace.dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.94", features = ["extra-traits"] }
